# ns__file unit: standard, comp: .nycrc.yml */
# ns__custom_start testCoverageThresholds */
check-coverage: false
branches: 17
lines: 40
functions: 29
statements: 40
# ns__custom_end testCoverageThresholds */
